- name: Setting up cron job for ansible-pull
  ansible.builtin.cron:
    name: "Ansible Pull Cron Job"
    user: ansible-pull
    minute: "*/30"
    job: "/usr/bin/ansible-pull -o -U https://github.com/gurkiratm/ansible_pull.git > /tmp/ansible-pull.log 2>&1"